# Generated by Django 5.2.7 on 2025-11-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_mills_units_ntn'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('pcs', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_invoice_items', to='webapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('pcs', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_invoice_items', to='webapp.invoice')),
            ],
        ),
    ]
